//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "heart_rate")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub bpm: i16,
    pub time: DateTime,
    #[sea_orm(column_type = "Text")]
    pub rr_intervals: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
