//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::activities::Entity as Activities;
pub use super::heart_rate::Entity as HeartRate;
pub use super::packets::Entity as Packets;
pub use super::sleep_cycles::Entity as SleepCycles;
